import * as Notifications from 'expo-notifications';
import * as IntentLauncher from 'expo-intent-launcher';
import { createAudioPlayer } from 'expo-audio';
import { Platform as RNPlatform } from 'react-native';
import type { AlertPrefs, NotificationService } from '../types';

/** Bundled soft two-note chime (generated by scripts/make-chime.js; original work, no license needed). */
const SOUND_FILE = 'alphadex_chime.wav';
const CHIME = require('../../../assets/sounds/alphadex_chime.wav');
const PACKAGE = 'com.alphadron.app';

// Android fixes a channel's sound once it exists, and a channel the system or user has muted stays
// muted. The version suffix lets us start fresh channels if that ever happens.
const CH_GENTLE = 'alerts_gentle_v2';
const CH_ALARM = 'alerts_alarm_v2';
const CH_SILENT = 'alerts_silent_v2';
const OLD_CHANNELS = ['reminders', 'due_gentle', 'due_alarm', 'due_silent'];

let prefs: AlertPrefs = { sound: true, style: 'gentle' };

/** Plays the chime inside the app. Used while the app is open, where Android would otherwise decide. */
function playChime() {
  if (!prefs.sound) {
    return;
  }
  try {
    const player = createAudioPlayer(CHIME);
    player.volume = 1;
    const sub = player.addListener('playbackStatusUpdate', status => {
      if (status.didJustFinish) {
        sub.remove();
        player.remove();
      }
    });
    player.play();
  } catch {
    // The notification channel still plays it when the app is in the background.
  }
}

// While the app is open we show the banner and play the chime ourselves, so the sound never depends
// on channel state. When the app is closed or in the background, the channel's sound plays instead.
Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowBanner: true,
    shouldShowList: true,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
});
Notifications.addNotificationReceivedListener(() => playChime());

function channelId(): string {
  if (!prefs.sound) {
    return CH_SILENT;
  }
  return prefs.style === 'alarm' ? CH_ALARM : CH_GENTLE;
}

let channelsReady: Promise<void> | null = null;

function ensureChannels(): Promise<void> {
  if (RNPlatform.OS !== 'android') {
    return Promise.resolve();
  }
  if (!channelsReady) {
    channelsReady = (async () => {
      const common = {
        lockscreenVisibility: Notifications.AndroidNotificationVisibility.PUBLIC,
        enableLights: true,
        enableVibrate: true,
      };
      await Notifications.setNotificationChannelAsync(CH_GENTLE, {
        ...common,
        name: 'Due alerts',
        description: 'A soft chime when something is due',
        importance: Notifications.AndroidImportance.HIGH,
        sound: SOUND_FILE,
        vibrationPattern: [0, 180],
        audioAttributes: {
          usage: Notifications.AndroidAudioUsage.NOTIFICATION,
          contentType: Notifications.AndroidAudioContentType.SONIFICATION,
        },
      });
      await Notifications.setNotificationChannelAsync(CH_ALARM, {
        ...common,
        name: 'Due alerts (alarm volume)',
        description: 'Plays at alarm volume, so you hear it even when the phone is on silent',
        importance: Notifications.AndroidImportance.MAX,
        sound: SOUND_FILE,
        vibrationPattern: [0, 250, 150, 250],
        audioAttributes: {
          usage: Notifications.AndroidAudioUsage.ALARM,
          contentType: Notifications.AndroidAudioContentType.SONIFICATION,
        },
      });
      await Notifications.setNotificationChannelAsync(CH_SILENT, {
        ...common,
        name: 'Due alerts (silent)',
        description: 'Vibration only',
        importance: Notifications.AndroidImportance.DEFAULT,
        sound: null,
        vibrationPattern: [0, 120],
      });
      for (const old of OLD_CHANNELS) {
        await Notifications.deleteNotificationChannelAsync(old).catch(() => undefined);
      }
    })().catch(e => {
      channelsReady = null; // try again next time instead of caching a failure
      throw e;
    });
  }
  return channelsReady;
}

export const androidNotifications: NotificationService = {
  setAlertPrefs(p) {
    prefs = p;
  },

  async ensurePermission() {
    await ensureChannels();
    const cur = await Notifications.getPermissionsAsync();
    if (cur.granted) {
      return true;
    }
    const req = await Notifications.requestPermissionsAsync();
    return req.granted;
  },

  async schedule({ key, title, body, at, repeat }) {
    await ensureChannels();
    await Notifications.cancelScheduledNotificationAsync(key).catch(() => undefined);
    const T = Notifications.SchedulableTriggerInputTypes;
    const channel = channelId();
    let trigger: Notifications.NotificationTriggerInput;
    if (repeat === 'daily') {
      trigger = { type: T.DAILY, hour: at.getHours(), minute: at.getMinutes(), channelId: channel };
    } else if (repeat === 'weekly') {
      trigger = {
        type: T.WEEKLY,
        weekday: at.getDay() + 1, // expo: 1 = Sunday
        hour: at.getHours(),
        minute: at.getMinutes(),
        channelId: channel,
      };
    } else {
      trigger = { type: T.DATE, date: at, channelId: channel };
    }
    await Notifications.scheduleNotificationAsync({
      identifier: key,
      content: { title, body, sound: prefs.sound ? SOUND_FILE : false },
      trigger,
    });
  },

  async cancel(key) {
    await Notifications.cancelScheduledNotificationAsync(key).catch(() => undefined);
  },

  async showNow(title, body, afterSeconds = 1) {
    await ensureChannels();
    await Notifications.scheduleNotificationAsync({
      content: { title, body, sound: prefs.sound ? SOUND_FILE : false },
      trigger: {
        type: Notifications.SchedulableTriggerInputTypes.TIME_INTERVAL,
        seconds: Math.max(1, afterSeconds),
        channelId: channelId(),
      },
    });
  },

  async describeAlertChannel() {
    if (RNPlatform.OS !== 'android') {
      return 'Not available on this platform.';
    }
    await ensureChannels();
    const ch = await Notifications.getNotificationChannelAsync(channelId());
    if (!ch) {
      return 'The alert channel could not be read.';
    }
    const importance = Notifications.AndroidImportance[ch.importance] ?? String(ch.importance);
    const sound = ch.sound ? 'custom chime' : 'no sound';
    const volume = ch.audioAttributes?.usage === Notifications.AndroidAudioUsage.ALARM ? 'alarm volume' : 'notification volume';
    return `Android channel: ${ch.name}, importance ${importance.toLowerCase()}, ${sound}, plays at ${volume}.`;
  },

  async openAlertSoundSettings() {
    try {
      await IntentLauncher.startActivityAsync('android.settings.CHANNEL_NOTIFICATION_SETTINGS', {
        extra: {
          'android.provider.extra.APP_PACKAGE': PACKAGE,
          'android.provider.extra.CHANNEL_ID': channelId(),
        },
      });
    } catch {
      await IntentLauncher.startActivityAsync('android.settings.APP_NOTIFICATION_SETTINGS', {
        extra: { 'android.provider.extra.APP_PACKAGE': PACKAGE },
      }).catch(() => undefined);
    }
  },

  async openExactAlarmSettings() {
    try {
      await IntentLauncher.startActivityAsync('android.settings.REQUEST_SCHEDULE_EXACT_ALARM', {
        data: `package:${PACKAGE}`,
      });
    } catch {
      // Older Android (before 12) has no such screen; alerts are already exact there.
    }
  },
};
