import * as Notifications from 'expo-notifications';
import * as IntentLauncher from 'expo-intent-launcher';
import { Platform as RNPlatform } from 'react-native';
import type { AlertPrefs, NotificationService } from '../types';

/** Bundled soft two-note chime (generated by scripts/make-chime.js; original work, no license needed). */
const SOUND_FILE = 'alphadex_chime.wav';
const PACKAGE = 'com.alphadron.app';

// Android fixes a channel's sound once created, so each style gets its own channel.
const CH_GENTLE = 'due_gentle';
const CH_ALARM = 'due_alarm';
const CH_SILENT = 'due_silent';

let prefs: AlertPrefs = { sound: true, style: 'gentle' };

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowBanner: true,
    shouldShowList: true,
    shouldPlaySound: true,
    shouldSetBadge: false,
  }),
});

function channelId(): string {
  if (!prefs.sound) {
    return CH_SILENT;
  }
  return prefs.style === 'alarm' ? CH_ALARM : CH_GENTLE;
}

let channelsReady: Promise<void> | null = null;

function ensureChannels(): Promise<void> {
  if (RNPlatform.OS !== 'android') {
    return Promise.resolve();
  }
  if (!channelsReady) {
    channelsReady = (async () => {
      const common = {
        lockscreenVisibility: Notifications.AndroidNotificationVisibility.PUBLIC,
        enableLights: true,
        enableVibrate: true,
      };
      await Notifications.setNotificationChannelAsync(CH_GENTLE, {
        ...common,
        name: 'Due alerts',
        description: 'A soft chime when something is due',
        importance: Notifications.AndroidImportance.HIGH,
        sound: SOUND_FILE,
        vibrationPattern: [0, 180],
        audioAttributes: {
          usage: Notifications.AndroidAudioUsage.NOTIFICATION,
          contentType: Notifications.AndroidAudioContentType.SONIFICATION,
        },
      });
      await Notifications.setNotificationChannelAsync(CH_ALARM, {
        ...common,
        name: 'Due alerts (alarm volume)',
        description: 'Plays at alarm volume, so you hear it even when the phone is on silent',
        importance: Notifications.AndroidImportance.MAX,
        sound: SOUND_FILE,
        vibrationPattern: [0, 250, 150, 250],
        audioAttributes: {
          usage: Notifications.AndroidAudioUsage.ALARM,
          contentType: Notifications.AndroidAudioContentType.SONIFICATION,
        },
      });
      await Notifications.setNotificationChannelAsync(CH_SILENT, {
        ...common,
        name: 'Due alerts (silent)',
        description: 'Vibration only',
        importance: Notifications.AndroidImportance.DEFAULT,
        sound: null,
        vibrationPattern: [0, 120],
      });
      // The first version of the app used a single default-sound channel.
      await Notifications.deleteNotificationChannelAsync('reminders').catch(() => undefined);
    })();
  }
  return channelsReady;
}

export const androidNotifications: NotificationService = {
  setAlertPrefs(p) {
    prefs = p;
  },

  async ensurePermission() {
    await ensureChannels();
    const cur = await Notifications.getPermissionsAsync();
    if (cur.granted) {
      return true;
    }
    const req = await Notifications.requestPermissionsAsync();
    return req.granted;
  },

  async schedule({ key, title, body, at, repeat }) {
    await ensureChannels();
    await Notifications.cancelScheduledNotificationAsync(key).catch(() => undefined);
    const T = Notifications.SchedulableTriggerInputTypes;
    const channel = channelId();
    let trigger: Notifications.NotificationTriggerInput;
    if (repeat === 'daily') {
      trigger = { type: T.DAILY, hour: at.getHours(), minute: at.getMinutes(), channelId: channel };
    } else if (repeat === 'weekly') {
      trigger = {
        type: T.WEEKLY,
        weekday: at.getDay() + 1, // expo: 1 = Sunday
        hour: at.getHours(),
        minute: at.getMinutes(),
        channelId: channel,
      };
    } else {
      trigger = { type: T.DATE, date: at, channelId: channel };
    }
    await Notifications.scheduleNotificationAsync({
      identifier: key,
      content: { title, body, sound: prefs.sound ? SOUND_FILE : false },
      trigger,
    });
  },

  async cancel(key) {
    await Notifications.cancelScheduledNotificationAsync(key).catch(() => undefined);
  },

  async showNow(title, body) {
    await ensureChannels();
    await Notifications.scheduleNotificationAsync({
      content: { title, body, sound: prefs.sound ? SOUND_FILE : false },
      trigger: { type: Notifications.SchedulableTriggerInputTypes.TIME_INTERVAL, seconds: 1, channelId: channelId() },
    });
  },

  async openExactAlarmSettings() {
    try {
      await IntentLauncher.startActivityAsync('android.settings.REQUEST_SCHEDULE_EXACT_ALARM', {
        data: `package:${PACKAGE}`,
      });
    } catch {
      // Older Android (before 12) has no such screen; alerts are already exact there.
    }
  },
};
