// Synthesises the app's alert sound: a soft two-note bell (E5 then A5).
// Original work generated by this script, so it carries no third-party license.
const fs = require('fs');

const RATE = 44100;
const DURATION = 1.8;
const total = Math.floor(RATE * DURATION);
const samples = new Float32Array(total);

function bell(startSec, freq, gain) {
  const start = Math.floor(startSec * RATE);
  for (let i = 0; start + i < total; i++) {
    const t = i / RATE;
    const attack = Math.min(1, t / 0.006); // 6 ms fade-in: no click
    const decay = Math.exp(-t / 0.42);
    // A bell is a fundamental plus a few quieter, faster-fading overtones.
    const tone =
      Math.sin(2 * Math.PI * freq * t) +
      0.35 * Math.sin(2 * Math.PI * freq * 2.0 * t) * Math.exp(-t / 0.25) +
      0.18 * Math.sin(2 * Math.PI * freq * 3.01 * t) * Math.exp(-t / 0.15);
    samples[start + i] += gain * attack * decay * tone;
  }
}

bell(0.0, 659.25, 0.5); // E5
bell(0.26, 880.0, 0.5); // A5

// Normalise to a comfortable peak, fade the tail to silence.
let peak = 0;
for (const s of samples) peak = Math.max(peak, Math.abs(s));
const scale = 0.7 / peak;
const pcm = Buffer.alloc(total * 2);
for (let i = 0; i < total; i++) {
  const tail = Math.min(1, (total - i) / (RATE * 0.05));
  pcm.writeInt16LE(Math.round(samples[i] * scale * tail * 32767), i * 2);
}

const header = Buffer.alloc(44);
header.write('RIFF', 0);
header.writeUInt32LE(36 + pcm.length, 4);
header.write('WAVE', 8);
header.write('fmt ', 12);
header.writeUInt32LE(16, 16);
header.writeUInt16LE(1, 20); // PCM
header.writeUInt16LE(1, 22); // mono
header.writeUInt32LE(RATE, 24);
header.writeUInt32LE(RATE * 2, 28);
header.writeUInt16LE(2, 32);
header.writeUInt16LE(16, 34);
header.write('data', 36);
header.writeUInt32LE(pcm.length, 40);

fs.writeFileSync(__dirname + '/../assets/sounds/alphadex_chime.wav', Buffer.concat([header, pcm]));
console.log('wrote alphadex_chime.wav', total / RATE + 's', Math.round((44 + pcm.length) / 1024) + ' KB');
